# Generated by Django 4.1 on 2022-08-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150)),
                ('category_slug', models.SlugField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150)),
                ('price', models.IntegerField()),
                ('mojodi', models.BooleanField(default=True)),
                ('text', models.TextField()),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(to='store.category')),
            ],
        ),
    ]
