# Generated by Django 4.1 on 2022-08-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_orderdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='order',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order',
            field=models.ManyToManyField(to='store.order'),
        ),
    ]
