# Generated by Django 4.1 on 2022-08-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_orderdetail_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
